# Generated by Django 2.1.2 on 2019-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190121_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
