# Generated by Django 2.1.2 on 2019-02-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
