# Generated by Django 2.1.2 on 2019-01-18 08:25

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='photo',
            field=models.ImageField(default=None, upload_to=listings.models.listing_upload_path),
        ),
    ]
