# Generated by Django 2.1.2 on 2019-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190118_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.FloatField(default=None),
        ),
    ]
