# Generated by Django 2.1.2 on 2019-01-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190118_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AL', 'al'), ('AK', 'ak'), ('AZ', 'az'), ('AR', 'ar'), ('CA', 'ca'), ('CO', 'co'), ('CT', 'ct'), ('DC', 'dc'), ('DE', 'de'), ('FL', 'fl'), ('GA', 'ga'), ('HI', 'hi'), ('ID', 'id'), ('IL', 'il'), ('IN', 'in'), ('IA', 'ia'), ('KS', 'ks'), ('KY', 'ky'), ('LA', 'la'), ('ME', 'me'), ('MD', 'md'), ('MA', 'ma'), ('MI', 'mi'), ('MN', 'mn'), ('MS', 'ms'), ('MO', 'mo'), ('MT', 'mt'), ('NE', 'ne'), ('NV', 'nv'), ('NH', 'nh'), ('NJ', 'nj'), ('NM', 'nm'), ('NY', 'ny'), ('NC', 'nc'), ('ND', 'nd'), ('OH', 'oh'), ('OK', 'ok'), ('OR', 'or'), ('PA', 'pa'), ('RI', 'ri'), ('SC', 'sc'), ('SD', 'sd'), ('TN', 'tn'), ('TX', 'tx'), ('UT', 'ut'), ('VT', 'vt'), ('VA', 'va'), ('WA', 'wa'), ('WV', 'wv'), ('WI', 'wi'), ('WY', 'wy')], max_length=2),
        ),
    ]
