# Generated by Django 2.1.2 on 2019-01-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20190119_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APT', 'Apartment'), ('CONDO', 'Condominium')], default=('HOUSE', 'House'), max_length=100),
        ),
    ]
