# Generated by Django 2.1.2 on 2019-01-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20190119_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='apt_number',
            new_name='apartment_number',
        ),
    ]
