# Generated by Django 2.1.2 on 2019-01-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20190119_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='apartment_number',
            new_name='unit_number',
        ),
    ]
