# Generated by Django 2.1.2 on 2019-01-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20190119_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
