# Generated by Django 2.1.2 on 2019-01-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20190119_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
    ]
