# Generated by Django 2.1.2 on 2019-01-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_remove_listingphoto_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
