# Generated by Django 2.1.2 on 2019-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20190118_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Realtor Name'),
        ),
    ]
