# Generated by Django 2.1.2 on 2019-01-28 00:28

from django.db import migrations, models
import realtors.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20190121_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default=None, upload_to=realtors.models.realtor_img_path),
        ),
    ]
